// Fetch the webfonts and write data/fonts.css with them base64-embedded, so the
// built HTML renders identically on any machine with no network. Without this the
// page pulls JetBrains Mono from Google Fonts at load time; on a machine that is
// offline (or where fonts.googleapis.com is blocked) every label, band, legend and
// address silently falls back to Consolas/Courier and the whole design changes.
// Both faces are variable fonts, so one file each covers all weights.
// Run: node scripts/embed-fonts.mjs   (only needed if the fonts ever change)
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36";

const FACES = [
  { family: "JetBrains Mono", css: "JetBrains+Mono:wght@400;500;600;700", weight: "100 800" },
  { family: "Inter", css: "Inter:wght@400;600;700", weight: "100 900" },
];

async function latinWoff2(spec) {
  const css = await (await fetch(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`, { headers: { "user-agent": UA } })).text();
  // Take the @font-face block whose unicode-range covers basic latin.
  const block = css.split("@font-face").find((b) => /unicode-range:[^;]*U\+0000/.test(b));
  const url = block && /src:\s*url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
  if (!url) throw new Error(`no latin woff2 found for ${spec}`);
  const buf = Buffer.from(await (await fetch(url, { headers: { "user-agent": UA } })).arrayBuffer());
  return buf;
}

let out = "/* Embedded webfonts — generated by scripts/embed-fonts.mjs. Do not hand-edit. */\n";
for (const f of FACES) {
  const buf = await latinWoff2(f.css);
  out += `@font-face{font-family:"${f.family}";font-style:normal;font-weight:${f.weight};font-display:swap;`
       + `src:url(data:font/woff2;base64,${buf.toString("base64")}) format("woff2")}\n`;
  console.log(`${f.family}: ${(buf.length / 1024).toFixed(0)} KB`);
}
writeFileSync(join(ROOT, "data", "fonts.css"), out);
console.log(`wrote data/fonts.css (${(out.length / 1024).toFixed(0)} KB)`);
